import util.Input;

public class ExceptionLec {

    static Input input = new Input();

    public static void main(String[] args) {

//        int [] numbers = {1,2,3};
//        System.out.println("before the exception");
//        try {
//            System.out.println("step 1: ");
//            System.out.println(numbers[999]);
//            System.out.println("step 2: requires step 1 to be completed");
//        } catch (Exception e){
//            System.out.println("wrong size of the array");
//        } finally {
//            System.out.println("after the exception");
//        }
//
//
//        try {
//            System.out.println(5 / 0);
//        } catch (ArithmeticException e){
//            System.out.println("You can't divide by 0 in JAVA");
//            e.getStackTrace();
//        } catch (Exception e){
//            System.out.println("A general order");
//        } finally {
//            System.out.println("I'm still working");
//        }
        System.out.println("ayyyoooo?");
        double userInput = input.getDouble();
        System.out.println(userInput);


    }
    

}
